### ISSUE TITLE
PostgreSQL performance tuning

### ISSUE THREAD

**Issue by Web3Slimchance** [IndexerDAO/IndexerDAO#31]
## Workshop page
https://github.com/IndexerDAO/tuning-postgresql/tree/main/docs

## Commonly Tuned Parameters

| Name | Description | Recommended starting point |
| --- | --- | --- | 
| [shared_buffers](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-SHARED-BUFFERS) | Sets the amount of memory the database server uses for shared memory buffers.  | LEAST(RAM/2, 10GB) |
| [wal_buffers](https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-WAL-BUFFERS) | The amount of shared memory used for WAL data that has not yet been written to disk. | 64MB |
| [effective_cache_size](https://www.postgresql.org/docs/current/runtime-config-query.html#GUC-EFFECTIVE-CACHE-SIZE) |  Sets the planner's assumption about the effective size of the disk cache that is available to a single query. This is factored into estimates of the cost of using an index; a higher value makes it more likely index scans will be used, a lower value makes it more likely sequential scans will be used.  | smaller value of either 0.75* total ram amount, "or the sum of buff/cache, free ram and shared buffers in the output of free command" |
|  [work_mem](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-WORK-MEM) |  Sets the base maximum amount of memory to be used by a query operation (such as a sort or hash table) before writing to temporary disk files. | ((Total RAM - shared_buffers)/(16 x CPU cores)) |
| [maintenance_work_mem](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-MAINTENANCE-WORK-MEM) | This determines the maximum amount of memory used for maintenance operations like VACUUM, CREATE INDEX, ALTER TABLE ADD FOREIGN KEY, and data-loading operations. | value of 1GB is a good start |
| [autovacuum](https://www.postgresql.org/docs/current/runtime-config-autovacuum.html#GUC-AUTOVACUUM) | Controls whether the server should run the autovacuum launcher daemon. This is on by default; however, track_counts must also be enabled for autovacuum to work. |
| [max_connections](https://www.postgresql.org/docs/current/runtime-config-connection.html#GUC-MAX-CONNECTIONS) |  Determines the maximum number of concurrent connections to the database server. | GREATEST(4 x CPU cores, 100) |
| [autovacuum_work_mem](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-AUTOVACUUM-WORK-MEM) |  Specifies the maximum amount of memory to be used by each autovacuum worker process. |
| [effective_io_concurrency](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-EFFECTIVE-IO-CONCURRENCY) |  Sets the number of concurrent disk I/O operations that PostgreSQL expects can be executed simultaneously. |
| [max_prepared_transactions](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-MAX-PREPARED-TRANSACTIONS) | Sets the maximum number of transactions that can be in the “prepared” state simultaneously. If you are not planning to use prepared transactions, this parameter should be set to zero to prevent accidental creation of prepared transactions. If you are using prepared transactions, you will probably want max_prepared_transactions to be at least as large as max_connections, so that every session can have a prepared transaction pending. |
| [max_fsm_pages](https://www.postgresql.org/docs/8.3/runtime-config-resource.html#GUC-MAX-FSM-PAGES) |  Sets the maximum number of disk pages for which free space will be tracked in the shared free-space map.  |  
| [synchronous_commit](https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-SYNCHRONOUS-COMMIT) | Specifies how much WAL processing must complete before the database server returns a “success” indication to the client. Valid values are remote_apply, on (the default), remote_write, local, and off. |
| [fsync](https://www.postgresql.org/docs/8.1/runtime-config-wal.html#GUC-FSYNC) |  If this option is on, the PostgreSQL server will try to make sure that updates are physically written to disk, by issuing fsync() system calls or various equivalent methods (see [wal_sync_method](https://www.postgresql.org/docs/8.1/runtime-config-wal.html#GUC-WAL-SYNC-METHOD)). This ensures that the database cluster can recover to a consistent state after an operating system or hardware crash. |

**Comment by alex-pakalniskis** [comment]
I reached out to Nodeify to share any resources he recommends. Will post them here.

**Comment by alex-pakalniskis** [comment]
# Notes on [Optimize PostgreSQL Server Performance Through Configuration](https://www.crunchydata.com/blog/optimize-postgresql-server-performance)

## [shared_buffers](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-SHARED-BUFFERS)
* PostgreSQL uses 'double buffering', meaning that PostgreSQL uses its own internal buffer as well as kernel buffered IO. In short, this means that data is stored in memory twice.
* The PostgreSQL buffer is named [shared_buffers](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-SHARED-BUFFERS) and it defines how much dedicated system memory PostgreSQL will use for cache.
  * Because of PostgreSQL's design choice to ensure compatibility on all supported machines and operating systems, this value is set conservatively low by default. 
* Generally speaking, the value for shared_buffers should be roughly 25% of the total system RAM for a dedicated DB server. 
  * The value for shared_buffers should never be set to reserve all of the system RAM for PostgreSQL. 
  * A value over 25% of the system RAM can be useful if, for example, it is set such that the entire database working set of data can fit in cache, as this would greatly reduce the amount of time reading from disk.
  * Alternately, while a larger shared_buffers value can increase performance in 'read heavy' use cases, having a large shared_buffer value can be detrimental for 'write heavy' use cases, as the entire contents of shared_buffers must be processed during writes.


## wal_buffers

## effective_cache_size

## maintenance_work_mem

**Comment by alex-pakalniskis** [comment]
# Notes on [Tuning Your PostgreSQL Server](https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server) 
* PostgreSQL ships with a basic configuration tuned for wide compatibility rather than performance.
  * Odds are good the default parameters are very undersized for your system. 
* This is a sprint through a simplified view of the basics, with a look at the most common things people new to PostgreSQL aren't aware of.

## [max_connections](http://www.postgresql.org/docs/current/static/runtime-config-connection.html#GUC-MAX-CONNECTIONS)
 * max_connections sets exactly that: the maximum number of client connections allowed. 
 * This is very important to some of the below parameters (particularly work_mem) because there are some memory resources that are or can be allocated on a per-client basis, so the maximum number of clients suggests the maximum possible memory use. 
 * Generally, PostgreSQL on good hardware can support a few hundred connections. 
   * If you want to have thousands instead, you should consider using [connection pooling software](https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling) to reduce the connection overhead.

**Comment by alex-pakalniskis** [comment]
# Notes on [Performance Tuning PostgreSQL](https://www.revsys.com/writings/postgresql-performance.html)
* The default configuration PostgreSQL ships with is a very solid configuration aimed at everyone's best guess as to how an "average" database on "average" hardware should be setup. This article aims to help PostgreSQL users of all levels better understand PostgreSQL performance tuning.

## Query Lifecycle
* Transmission of query string to database backend
  * There isn't much you can tune about this step, however if you have a very large queries that cannot be prepared in advance it may help to put them into the database as a stored procedure and cut the data transfer down to a minimum.
* Parsing of query string
  * Once the SQL query is inside the database server it is parsed into tokens. This step can also be minimized by using stored procedures.
* Planning of query to optimize retrieval of data
  * This stage checks to see if the query is already prepared if your version of PostgreSQL and client library support this feature.
  * It also analyzes your SQL to determine what the most efficient way of retrieving your data is. Should we use an index and if so which one? Maybe a hash join on those two tables is appropriate?
  * These are some of the decisions the database makes at this point of the process. This step can be eliminated if the query is previously prepared.
* Retrieval of data from hardware
  * While there are some tuning options that help here, this step is mostly effected by your hardware configuration.
* Transmission of results to client
  * While there aren't any real tuning options for this step, you should be aware that all of the data that you are returning is pulled from the disk and sent over the wire to your client. 
  * Minimizing the number of rows and columns to only those that are necessary can often increase your performance.

## General Tuning
### max_connections
* This option sets the maximum number of database backend to have at any one time.
* Use this feature to ensure that you do not launch so many backends that you begin swapping to disk and kill the performance of all the children. 
  * Depending on your application it may be better to deny the connection entirely rather than degrade the performance of all of the other children.

### shared_buffers
* Editing this option is the simplest way to improve the performance of your database server. 
  * The default is pretty low for most modern hardware. 
  * General wisdom says that this should be set to roughly 25% of available RAM on the system. 
  * Like most of the options I will outline here you will simply need to try them at different levels (both up and down ) and see how well it works on your particular system.
  * Most people find that setting it larger than a third starts to degrade performance.

**Comment by alex-pakalniskis** [comment]
# Notes on [Understanding Postgres Performance](https://www.craigkerstiens.com/2012/10/01/understanding-postgres-performance/)
* Without becoming a DBA there’s a few pieces of data that most application developers can easily grok which will help them understand if their database is performing adequately.

## Understanding your Cache and its Hit Rate
* The typical rule for most applications is that only a fraction of its data is regularly accessed. 
  * As with many other things data can tend to follow the 80/20 rule with 20% of your data accounting for 80% of the reads and often times its higher than this. 
  * Postgres itself actually tracks access patterns of your data and will on its own keep frequently accessed data in cache.
  * Generally you want your database to have a cache hit rate of about 99%.

``` sql
SELECT 
  sum(heap_blks_read) as heap_read,
  sum(heap_blks_hit)  as heap_hit,
  sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read)) as ratio
FROM 
  pg_statio_user_tables;
```
* If you find yourself with a ratio significantly lower than 99% then you likely want to consider increasing the cache available to your database

## Understanding Index Usage
* Several frameworks will add indexes on your primary keys, though if you’re searching on other fields or joining heavily you may need to manually add such indexes.
* Indexes are most valuable across large tables as well. While accessing data from cache is faster than disk, even data within memory can be slow if Postgres must parse through hundreds of thousands of rows to identify if they meet a certain condition. 
* To generate a list of your tables in your database with the largest ones first and the percentage of time which they use an index you can run:
``` sql
SELECT 
  relname, 
  100 * idx_scan / (seq_scan + idx_scan) percent_of_times_index_used, 
  n_live_tup rows_in_table
FROM 
  pg_stat_user_tables
WHERE 
    seq_scan + idx_scan > 0 
ORDER BY 
  n_live_tup DESC;

```

* While there is no perfect answer, if you’re not somewhere around 99% on any table over 10,000 rows you may want to consider adding an index. 
* When examining where to add an index you should look at what kind of queries you’re running.
  * Generally you’ll want to add indexes where you’re looking up by some other id or on values that you’re commonly filtering on such as created_at fields.
* Pro tip: If you’re adding an index on a production database use CREATE INDEX CONCURRENTLY to have it build your index in the background and not hold a lock on your table. 
  * The limitation to creating indexes [concurrently](http://www.postgresql.org/docs/9.1/static/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY) is they can typically take 2-3 times longer to create and can’t be run within a transaction.
  * Though for any large production site these trade-offs are worth the trade-off in experience to your end users.

## Index Cache Hit Rate
* Finally to combine the two if you’re interested in how many of your indexes are within your cache you can run:

``` sql 
SELECT 
  sum(idx_blks_read) as idx_read,
  sum(idx_blks_hit)  as idx_hit,
  (sum(idx_blks_hit) - sum(idx_blks_read)) / sum(idx_blks_hit) as ratio
FROM 
  pg_statio_user_indexes;

```

* Generally, you should also expect this to be in the 99% similar to your regular cache hit rate.

**Comment by alex-pakalniskis** [comment]
Notes on [Herding elephants: Lessons learned from sharding Postgres at Notion](https://www.notion.so/blog/sharding-postgres-at-notion)

## Deciding when to shard
* When it comes to sharding, fast-growing startups must navigate a delicate tradeoff. 
* For us, the inflection point arrived when the Postgres VACUUM process began to stall consistently, preventing the database from reclaiming disk space from dead tuples.
  * While disk capacity can be increased, more worrying was the prospect of [transaction ID (TXID) wraparound](https://blog.sentry.io/2015/07/23/transaction-id-wraparound-in-postgres), a safety mechanism in which Postgres would stop processing all writes to avoid clobbering existing data.

## Designing a sharding scheme
* If you’ve never sharded a database before, here’s the idea: instead of vertically scaling a database with progressively heftier instances, horizontally scale by partitioning data across multiple databases
  * Now you can easily spin up additional hosts to accommodate growth. 
  * Unfortunately, now your data is in multiple places, so you need to design a system that maximizes performance and consistency in a distributed setting.


## Application-level sharding
* We decided to implement our own partitioning scheme and route queries from application logic, an approach known as application-level sharding. 
  * What data should we shard? 
  * How should we partition the data?
  * How many shards should we create? How should those shards be organized?

## Decision 1: Shard all data transitively related to block
* Since Notion’s [data model](https://www.notion.so/blog/data-model-behind-notion) revolves around the concept of a block, each occupying a row in our database, the block table was the highest-priority for sharding.
* We decided to shard all tables reachable from the block table via some kind of foreign key relationship.
  *  Not all of these tables needed to be sharded, but if a record was stored in the main database while its related block was stored on a different physical shard, we could introduce inconsistencies when writing to different datastores.

## Decision 2: Partition block data by workspace ID
* Choosing a good partition scheme depends heavily on the distribution and connectivity of the data; since Notion is a team-based product, our next decision was to partition data by workspace ID.³
* Each workspace is assigned a UUID upon creation, so we can partition the UUID space into uniform buckets. Because each row in a sharded table is either a block or related to one, and each block belongs to exactly one workspace, we used the workspace ID as the partition key. Since users typically query data within a single workspace at a time, we avoid most cross-shard joins.

## Decision 3: Capacity planning
* Instance type
* Number of physical and logical shards
* Number of instances
* Cost


## Migrating to shards
* For any migration, our general framework goes something like this:
  * Double-write: Incoming writes get applied to both the old and new databases.
  * Backfill: Once double-writing has begun, migrate the old data to the new database.
  * Verification: Ensure the integrity of data in the new database.
  * Switch-over: Actually switch to the new database. This can be done incrementally, e.g. double-reads, then migrate all reads.

## Difficult lessons learned
* Shard earlier
* Aim for a zero-downtime migration
* Introduce a combined primary key instead of a separate partition key

**Comment by alex-pakalniskis** [comment]
# Notes on [Priorities](https://wiki.postgresql.org/wiki/Priorities)

There are three main resources that PostgreSQL users, queries, and databases will contend for:
* Memory
* CPU
* Disk I/O

Of these, disk I/O is commonly a bottleneck for database applications, but that's not always the case.


## Is CPU really the bottleneck?
* People often complain of pegged (100%) CPU and assume that's the cause of database slowdowns. 
* That's not necessarily the case - a system may show an apparent 100% CPU use, but in fact be mainly limited by I/O bandwidth. 
* The key warning sign here is the presence of a high iowait cpu percentage ("%wa"), indicating that much of the apparent load is actually caused by delays in the I/O subsystem. 
* Rather than assuming that CPU contention is the issue, it's a good idea to use the available [Performance Analysis Tools](https://wiki.postgresql.org/wiki/Performance_Analysis_Tools) to get a better idea of where your system bottlenecks really are.

## Prioritizing CPU
* For adjusting the CPU priority of PostgreSQL processes, you can use "renice" (on UNIX systems), but it's a bit clumsy to do since you need to "renice" the backend of interest, not the client program connected to that backend.
* One significant limitation of "renice", or any approach based on the setpriority() call, is that on most UNIX-like platforms one must be root to lower the numerical priority value (i.e. schedule the process to run more urgently) of a process.
* Increasing the priority of important backends, via a root user's call to "renice", instead of lowering the priority of unimportant ones, may be more effective.

## Prioritizing I/O
* I/O is harder.
* Some operating systems offer I/O priorities for processes, like Linux's ionice, and you'd think you could use these in a similar way to how you use 'nice'. 
  * Unfortunately, that won't work particularly well, because a lot of the work PostgreSQL does - especially disk writes - are done via a separate background writer process working from memory shared by all backends.
  * Similarly, the write-ahead logs are managed by their own process via shared memory. 

## Prioritizing memory
* PostgreSQL does have some [tunable parameters](https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server) for memory use that are per-client, particularly [work_mem](http://www.postgresql.org/docs/current/static/runtime-config-resource.html#GUC-WORK-MEM) and [maintenance_work_mem](http://www.postgresql.org/docs/current/static/runtime-config-resource.html#GUC-MAINTENANCE-WORK-MEM). These may be set within a given connection to allow that backend to use more than the usual amount of memory for things like sorts and index creation.
* You cannot affect the shared memory allocation done with settings like shared_buffers this way, that value is fixed at database startup time and can't be changed without restarting it.

**Comment by alex-pakalniskis** [comment]
Some random tuning parameters: https://github.com/decred/dcrdata/blob/master/db/dcrpg/postgresql-tuning.conf

Suggests http://pgtune.leopard.in.ua/

**Comment by alex-pakalniskis** [comment]
Do baseline tuning to improve performance

**Comment by alex-pakalniskis** [comment]
# Things to change
## Huge Pages
> By default, the page size on Linux is 4kB. A typical PostgreSQL instance may allocate many GBs of memory, which will end up with potential performance problems with such a small page size. Also, given that these pages will be fragmented, using them for large data sets will end up with extra time for mapping them. 
> [- Fearing 2021](https://www.enterprisedb.com/postgres-tutorials/introduction-postgresql-performance-tuning-and-optimization#hugepages)

**Comment by alex-pakalniskis** [comment]
Can resume when we're out of MIPs QA testing mode and more in "regular" production indexing mode
